name: "Publish images digests to GitHub"
description: "Upload images digests to a GitHub release"
runs:
  using: "composite"
  steps:
    - name: Upload digests
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        gh release upload -R ${{ env.REPOSITORY_OWNER }}/rancher ${{ env.TAG }} "$ARTIFACTS_BASE_DIR/$LINUX_FILE" --clobber
        gh release upload -R ${{ env.REPOSITORY_OWNER }}/rancher ${{ env.TAG }} "$ARTIFACTS_BASE_DIR/$WINDOWS_FILE" --clobber
        gh release upload -R ${{ env.REPOSITORY_OWNER }}/rancher ${{ env.TAG }} "$ARTIFACTS_BASE_DIR/$CHECKSUM_FILE" --clobber
